name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # this run on our commits on main to open the RC Pull Request
  please-release-candidate:
    name: Create RC Pull Request
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        name: Run prerelease release-please
        uses: googleapis/release-please-action@v4.4.0
        with:
          config-file: ".github/release-candidate-please-config.json"
          manifest-file: ".github/.release-candidate-please-manifest.json"

  # this runs on commits from merged RC Pull Request
  please-release:
    name: Create Prerelease and Release Pull Request
    runs-on: ubuntu-latest
    if: ${{ needs.please-release-candidate.outputs.releases_created == 'true' && contains(needs.please-release-candidate.outputs.tag_name, 'rc') }}
    needs: [ please-release-candidate ]
    steps:
      - name: Run release release-please
        uses: googleapis/release-please-action@v4.4.0
        with:
          config-file: ".github/release-please-config.json"
          manifest-file: ".github/.release-please-manifest.json"
